package com.glucoze.thesismanagement.notification;

public enum NotificationType {
    REGISTRATION_SUBMITTED,
    REGISTRATION_APPROVED,
    REGISTRATION_REJECTED,
    REPORT_SUBMITTED,
    REPORT_RESUBMITTED,
    REPORT_REVISION_REQUIRED,
    REPORT_APPROVED,
    COUNCIL_ASSIGNED,
    DEFENSE_SCHEDULED,
    GRADING_TASK_ASSIGNED,
    RESULT_PUBLISHED
}
