package com.glucoze.thesismanagement.audit;

public enum AuditAction {
    USER_CREATE, USER_UPDATE, USER_ENABLE, USER_DISABLE, USER_PASSWORD_RESET, USER_DELETE,
    THESIS_CREATE, THESIS_UPDATE, THESIS_DELETE,
    REGISTRATION_APPROVE, REGISTRATION_REJECT,
    REPORT_REVISION_REQUEST, REPORT_APPROVE,
    COUNCIL_CREATE, COUNCIL_UPDATE, COUNCIL_DELETE,
    COUNCIL_MEMBER_ADD, COUNCIL_MEMBER_REMOVE,
    SCHEDULE_CREATE, GRADE_CREATE, GRADE_UPDATE, RESULT_PUBLISH
}
